<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVedxxzi\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVedxxzi/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVedxxzi.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVedxxzi\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerVedxxzi\appTestDebugProjectContainer([
    'container.build_hash' => 'Vedxxzi',
    'container.build_id' => '0ed5aa65',
    'container.build_time' => 1551466020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVedxxzi');
