<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIrswjxg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIrswjxg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIrswjxg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIrswjxg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIrswjxg\appDevDebugProjectContainer([
    'container.build_hash' => 'Irswjxg',
    'container.build_id' => 'fed6675b',
    'container.build_time' => 1551469147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIrswjxg');
