<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxdcrrp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxdcrrp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPxdcrrp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPxdcrrp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPxdcrrp\appDevDebugProjectContainer([
    'container.build_hash' => 'Pxdcrrp',
    'container.build_id' => 'e7a448d6',
    'container.build_time' => 1551466010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxdcrrp');
